### ISSUE TITLE
The original version of DMTCP

### ISSUE THREAD

**Issue by GoodKairos** [DMTCP-CRAC/CRAC-early-development#4]
Hi,

Could you tell me the version and branch of DMTCP which CRAC master is basing on?

Thank you very much.

GoodKairos

**Comment by gc00** [comment]
@JainTwinkle , Could you reply to this with the best place to look for examining the early version of CRAC?

**Comment by jrwellshpc** [comment]
The version file in the root of this repository says 3.0.0.

**Comment by JainTwinkle** [comment]
That's correct! It's based on DMTCP v3.0.0.
